### ISSUE TITLE
Memex ext cannot talk to local server

### ISSUE THREAD

**Issue by poltak** [WorldBrain/local-backup-server#6] opened 2019-03-22 04:20 UTC
I have tried to use the 0.4.0 version on macOS 10.13.6, however the extension can never talk to the local server after a backup folder is set up via the backup app's UI. 

Pressing the "I'm ready" button in the ext, I can see it is trying to GET `http://localhost:11922/status`, although this always fails. I can see nothing running on that 11922 port locally.

Ideas:
1. some third party software blocking it from running on that port
2. it's running somewhere else
3. it's encountering some error but not yet reflected in the UI

How do I see the stdout/stderr for the backup app?

**Comment by poltak** [comment] 2019-03-22 04:20
Originally found this from discussion in https://github.com/WorldBrain/Memex/pull/743

**Comment by poltak** [comment] 2019-03-25 01:43
It works if I download the source code and follow the instructions in the README to get it running.

**Comment by hgezim** [comment] 2020-04-15 18:23
Thanks @poltak. There was a key system prompt I wasn't seeing with released version that asks to allow incoming connections. Works when running from source.

**Comment by awendland** [comment] 2020-07-01 00:17
I'm also running into issues with accessing the program from the released version (I tested with [0.5.2](https://github.com/WorldBrain/local-backup-server/releases/tag/0.5.2)). Similarly, once I run `local-backup-server` from a git cloned version of the repo it proceeds to work fine (yay!).

What is the key system prompt that I'm missing for the release version? Would it be possible to add a UX flow for triggering and approving this prompt if necessary?

**Comment by blackforestboi** [comment] 2020-07-02 07:50
@awendland Ah damn, still :(

Which system OS are you on, and what are the exact workflows that you expected to work and didn't?

**Comment by awendland** [comment] 2020-07-02 20:37
System: `macOS Catalina version 10.15.5 (19F101)`

Workflow:
1. Open Memex dashboard
2. Navigate to settings > Backup & Restore
3. Select automated backup
4. Select local backup
5. Download the 0.5.2 version of the local-backup-server from the popup window
6. Unzip the local-backup-server
7. Run the .app program in the unzipped file
8. Open security & privacy and click "allow anyways" since the app is unsigned
9. Relaunch the application and accept the "this is from an unidentified developer prompt"
10. See the local-backup-server popup menu in the top left of my screen. Choose a folder inside my mounted Google Drive File Stream.
11. Click "confirm"
12. Attempt to proceed with setting up the automated backups from the Memex extension settings page but fail to proceed because it can't detect the server

I confirmed that the server isn't running correctly by `curl -v http://localhost:11922/status` which said `curl: (7) Failed to connect to localhost port 11922: Connection refused`. The local-backup-server menu item was appearing in the macOS status bar however clicking "open backup folder" did nothing.

When I switched to cloning this repo (commit 6a0ea2a8) and running it manually (after installing nw using `yarn global add nw` and then `nw .` in the repo root) the previous curl command started returning `running` and the Memex extension settings page let me proceed with setting up automatic local backups.

Let me know if there's more information I could provide!

**Comment by blackforestboi** [comment] 2020-07-06 18:18
thanks so much for all the investigation. 

it is SOO weird. everytime i test it locally with the zipped version that I will eventually upload, it all works. 
When I re-download that same .zip and then use it it doesn't.

Will investigate more

**Comment by blackforestboi** [comment] 2020-07-06 18:35
Ok I found the issue! https://apple.stackexchange.com/questions/321818/third-party-application-cannot-write-to-disk

You need to drag the file into the applications folder! Mac sandboxes apps.

**Comment by blackforestboi** [comment] 2020-07-06 18:56
Closing this now as issue is solved.

**Closed by blackforestboi** 2020-07-06 18:56 UTC
